# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='challan_prefix',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
