# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_challan_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name=b'Your Company')),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('office_address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=200)),
                ('pin_code', models.IntegerField(verbose_name=b'PIN Code')),
                ('cst_tin_number', models.CharField(max_length=300, verbose_name=b"Company's CST & TIN Number")),
                ('service_tax_number', models.CharField(max_length=200, verbose_name=b"Company's Service TAX Number")),
                ('pan_number', models.CharField(max_length=60, verbose_name=b"Company's PAN Number")),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
