# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('invoice', '0003_deliverychallan'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChallanItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name=b'DC Issued Date')),
                ('item', models.CharField(max_length=1000)),
                ('mou', models.CharField(choices=[(b'MTR', b'Meter'), (b'KG', b'Kilogram'), (b'GRAM', b'Gram'), (b'SFT', b'Square Feet'), (b'RMT', b'Running Meter'), (b'NOs', b'Number(s)'), (b'EA', b'Each'), (b'LTR', b'Litre'), (b'BOX', b'Box(s)'), (b'LOT', b'Lot(s)'), (b'JOB', b'Job(s)')], default=b'Nos', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('delivery_challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.DeliveryChallan')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.PurchaseOrder')),
            ],
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name=b'Line Description'),
        ),
    ]
