# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20170621_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverychallanitem',
            name='purchase_order',
        ),
    ]
