# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_deliverychallanitem_issue_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='deadline',
        ),
    ]
