# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_lineitem_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverychallanitem',
            old_name='item',
            new_name='particular',
        ),
        migrations.AddField(
            model_name='deliverychallanitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
