# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_due_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='estimated_payment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Estimated Payment Date'),
            preserve_default=False,
        ),
    ]
