# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('invoice', '0002_auto_20170620_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_number', models.CharField(blank=True, max_length=250, null=True)),
                ('goods_sent_through', models.CharField(blank=True, max_length=250, null=True)),
                ('work_order_number', models.CharField(blank=True, max_length=250, null=True)),
                ('work_order_date', models.DateField(verbose_name=b'Your work order date')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.PurchaseOrder')),
            ],
        ),
    ]
