# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_deliverychallan'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'DC Issued Date'),
        ),
    ]
