# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name=b'Deadline'),
        ),
    ]
